"use client";

import { FormEvent, useEffect, useState } from "react";
import type { User } from "@supabase/supabase-js";
import { isSupabaseConfigured, supabase } from "@/lib/supabase/client";

type Props = { onUserChange: (user: User | null) => void };

export function AccountPanel({ onUserChange }: Props) {
  const [user, setUser] = useState<User | null>(null), [open, setOpen] = useState(false), [mode, setMode] = useState<"login" | "signup">("login"), [email, setEmail] = useState(""), [password, setPassword] = useState(""), [name, setName] = useState(""), [gamertag, setGamertag] = useState(""), [message, setMessage] = useState("");
  useEffect(() => { if (!supabase) return; supabase.auth.getUser().then(({ data }) => { setUser(data.user); onUserChange(data.user); }); const { data: listener } = supabase.auth.onAuthStateChange((_event, session) => { setUser(session?.user ?? null); onUserChange(session?.user ?? null); }); return () => listener.subscription.unsubscribe(); }, [onUserChange]);
  if (!isSupabaseConfigured || !supabase) return null;
  async function submit(event: FormEvent) { event.preventDefault(); if (!supabase) return; setMessage(""); const result = mode === "signup" ? await supabase.auth.signUp({ email, password, options: { data: { display_name: name, gamertag } } }) : await supabase.auth.signInWithPassword({ email, password }); if (result.error) return setMessage(result.error.message); if (mode === "signup" && !result.data.session) setMessage("Check your email to confirm your account, then sign in."); else setOpen(false); }
  if (user) return <div className="flex items-center gap-3 text-right"><div><p className="text-xs font-bold uppercase text-white">{user.user_metadata.gamertag || user.email}</p><p className="text-[10px] uppercase text-zinc-400">Global leaderboard enabled</p></div><button onClick={() => { void supabase?.auth.signOut(); }} className="border border-white/25 px-2 py-1 text-[10px] font-bold uppercase hover:border-f1">Sign out</button></div>;
  return <><button onClick={() => setOpen(true)} className="border border-white/30 px-3 py-2 text-xs font-bold uppercase tracking-wider hover:border-white">Account</button>{open && <div className="fixed inset-0 z-50 grid place-items-center bg-black/75 p-4 backdrop-blur-sm"><form onSubmit={submit} className="w-full max-w-sm border border-white/15 bg-panel p-6"><div className="mb-5 flex items-center justify-between"><h2 className="text-2xl font-bold uppercase">{mode === "login" ? "Sign in" : "Create account"}</h2><button type="button" onClick={() => setOpen(false)} className="text-zinc-400">✕</button></div>{mode === "signup" && <><input required value={name} onChange={(event) => setName(event.target.value)} placeholder="Driver name" className="mb-3 w-full border border-white/15 bg-black/30 p-3 outline-none focus:border-f1" /><input required value={gamertag} onChange={(event) => setGamertag(event.target.value)} placeholder="Gamertag" className="mb-3 w-full border border-white/15 bg-black/30 p-3 outline-none focus:border-f1" /></>}<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="Email" className="mb-3 w-full border border-white/15 bg-black/30 p-3 outline-none focus:border-f1" /><input required type="password" minLength={6} value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Password (6+ characters)" className="mb-3 w-full border border-white/15 bg-black/30 p-3 outline-none focus:border-f1" />{message && <p className="mb-3 text-xs text-yellow-300">{message}</p>}<button className="w-full bg-f1 py-3 text-sm font-bold uppercase">{mode === "login" ? "Sign in" : "Create account"}</button><button type="button" onClick={() => { setMode(mode === "login" ? "signup" : "login"); setMessage(""); }} className="mt-4 w-full text-xs text-zinc-400 underline">{mode === "login" ? "Need an account? Sign up" : "Already have an account? Sign in"}</button></form></div>}</>;
}
