"use client";

import { FormEvent, useEffect, useState } from "react";
import type { User } from "@supabase/supabase-js";
import { isSupabaseConfigured, supabase } from "@/lib/supabase/client";

type Props = { onUserChange: (user: User | null) => void };
type Dialog = "auth" | "profile" | null;
const field = "mb-3 w-full border border-white/15 bg-black/30 p-3 text-sm outline-none focus:border-f1";

export function AccountPanel({ onUserChange }: Props) {
  const [user, setUser] = useState<User | null>(null), [dialog, setDialog] = useState<Dialog>(null), [mode, setMode] = useState<"login" | "signup">("login"), [email, setEmail] = useState(""), [password, setPassword] = useState(""), [name, setName] = useState(""), [gamertag, setGamertag] = useState(""), [inputSetup, setInputSetup] = useState("Wheel / Direct Drive"), [assistPreset, setAssistPreset] = useState("Unspecified"), [platform, setPlatform] = useState("PC"), [message, setMessage] = useState("");
  const loadProfile = (next: User | null) => { setUser(next); onUserChange(next); if (next) { setName(String(next.user_metadata.display_name || "")); setGamertag(String(next.user_metadata.gamertag || "")); setInputSetup(String(next.user_metadata.input_setup || "Wheel / Direct Drive")); setAssistPreset(String(next.user_metadata.assist_preset || "Unspecified")); setPlatform(String(next.user_metadata.platform || "PC")); } };

  useEffect(() => { if (!supabase) return; void supabase.auth.getUser().then(({ data }) => loadProfile(data.user)); const { data: listener } = supabase.auth.onAuthStateChange((_event, session) => loadProfile(session?.user ?? null)); return () => listener.subscription.unsubscribe(); }, [onUserChange]);
  if (!isSupabaseConfigured || !supabase) return null;
  const client = supabase;

  async function submitAuth(event: FormEvent) { event.preventDefault(); setMessage(""); const metadata = { display_name: name, gamertag, input_setup: inputSetup, assist_preset: assistPreset, platform }; const result = mode === "signup" ? await client.auth.signUp({ email, password, options: { data: metadata } }) : await client.auth.signInWithPassword({ email, password }); if (result.error) return setMessage(result.error.message); if (mode === "signup" && !result.data.session) setMessage("Check your email to confirm your account, then sign in."); else setDialog(null); }
  async function saveProfile(event: FormEvent) { event.preventDefault(); if (!user) return; setMessage(""); const metadata = { display_name: name.trim() || "Driver", gamertag: gamertag.trim() || "Driver", input_setup: inputSetup, assist_preset: assistPreset, platform }; const { data, error } = await client.auth.updateUser({ data: metadata }); if (error) return setMessage(error.message); await client.from("profiles").update({ display_name: metadata.display_name, gamertag: metadata.gamertag }).eq("id", user.id); loadProfile(data.user); setDialog(null); }
  const profileFields = <><input required value={name} onChange={(event) => setName(event.target.value)} placeholder="Driver name" className={field} /><input required value={gamertag} onChange={(event) => setGamertag(event.target.value)} placeholder="Gamertag" className={field} /><select value={inputSetup} onChange={(event) => setInputSetup(event.target.value)} className={field}><option>Wheel / Direct Drive</option><option>Wheel / Belt Drive</option><option>Controller</option><option>Keyboard</option></select><select value={assistPreset} onChange={(event) => setAssistPreset(event.target.value)} className={field}><option>Unspecified</option><option>No assists</option><option>Custom</option><option>Full assists</option></select><select value={platform} onChange={(event) => setPlatform(event.target.value)} className={field}><option>PC</option><option>PlayStation</option><option>Xbox</option></select></>;
  if (user) return <><div className="flex items-center gap-2 text-right"><div><p className="text-xs font-bold uppercase text-white">{user.user_metadata.gamertag || user.email}</p><p className="text-[10px] uppercase text-zinc-300">Global leaderboard enabled</p></div><button onClick={() => { setMessage(""); setDialog("profile"); }} className="border border-white/25 px-2 py-1 text-[10px] font-bold uppercase hover:border-white">Profile</button><button onClick={() => { void client.auth.signOut(); }} className="border border-white/25 px-2 py-1 text-[10px] font-bold uppercase hover:border-white">Sign out</button></div>{dialog === "profile" && <div className="fixed inset-0 z-50 grid place-items-center bg-black/75 p-4 backdrop-blur-sm"><form onSubmit={saveProfile} className="w-full max-w-sm border border-white/15 bg-panel p-6"><div className="mb-5 flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-f1">Account settings</p><h2 className="text-2xl font-bold uppercase">Driver profile</h2></div><button type="button" onClick={() => setDialog(null)} className="text-zinc-400">✕</button></div>{profileFields}{message && <p className="mb-3 text-xs text-yellow-300">{message}</p>}<button className="w-full bg-f1 py-3 text-sm font-bold uppercase">Save profile</button></form></div>}</>;
  return <><button onClick={() => { setMessage(""); setDialog("auth"); }} className="border border-white/30 px-3 py-2 text-xs font-bold uppercase tracking-wider hover:border-white">Sign in</button>{dialog === "auth" && <div className="fixed inset-0 z-50 grid place-items-center bg-black/75 p-4 backdrop-blur-sm"><form onSubmit={submitAuth} className="w-full max-w-sm border border-white/15 bg-panel p-6"><div className="mb-5 flex items-center justify-between"><h2 className="text-2xl font-bold uppercase">{mode === "login" ? "Sign in" : "Create account"}</h2><button type="button" onClick={() => setDialog(null)} className="text-zinc-400">✕</button></div>{mode === "signup" && profileFields}<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="Email" className={field} /><input required type="password" minLength={6} value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Password (6+ characters)" className={field} />{message && <p className="mb-3 text-xs text-yellow-300">{message}</p>}<button className="w-full bg-f1 py-3 text-sm font-bold uppercase">{mode === "login" ? "Sign in" : "Create account"}</button><button type="button" onClick={() => { setMode(mode === "login" ? "signup" : "login"); setMessage(""); }} className="mt-4 w-full text-xs text-zinc-400 underline">{mode === "login" ? "Need an account? Sign up" : "Already have an account? Sign in"}</button></form></div>}</>;
}
