"use client";

import { useEffect, useState } from "react";
import { formatMs, type TrackInfo } from "@/lib/telemetry";
import { supabase } from "@/lib/supabase/client";

type Lap = { id: string; driver_name: string; gamertag: string; car: string; lap_time_ms: number; recorded_at: string; input_setup: string; assist_preset: string; weather: string; platform: string; source_verified: boolean };
export function GlobalLeaderboard({ track }: { track: TrackInfo }) {
  const [laps, setLaps] = useState<Lap[]>([]);
  const [car, setCar] = useState(""), [input, setInput] = useState(""), [assists, setAssists] = useState(""), [weather, setWeather] = useState("");
  useEffect(() => { const client = supabase; if (!client || track.id < 0) return; const load = () => { let query = client.from("laps").select("id,driver_name,gamertag,car,lap_time_ms,recorded_at,input_setup,assist_preset,weather,platform,source_verified").eq("track_id", track.id).eq("valid", true).eq("source_verified", true).order("lap_time_ms").limit(25); if (car) query = query.ilike("car", `%${car}%`); if (input) query = query.eq("input_setup", input); if (assists) query = query.eq("assist_preset", assists); if (weather) query = query.eq("weather", weather); return query.then(({ data }) => setLaps(data || [])); }; void load(); const channel = client.channel(`track-${track.id}`).on("postgres_changes", { event: "INSERT", schema: "public", table: "laps", filter: `track_id=eq.${track.id}` }, load).subscribe(); return () => { client.removeChannel(channel); }; }, [track.id, car, input, assists, weather]);
  if (!supabase) return null;
  return <section className="mt-5 overflow-hidden border border-white/10 bg-panel"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-white/10 px-4 py-3"><div><p className="text-[10px] font-bold uppercase tracking-[.22em] text-f1">Worldwide</p><h2 className="text-xl font-bold uppercase">{track.name} all-time</h2></div><span className="text-xs text-zinc-400">VERIFIED TOP 25</span></div><div className="grid gap-2 border-b border-white/10 p-3 sm:grid-cols-4"><input value={car} onChange={(event) => setCar(event.target.value)} placeholder="Filter team / car" className="border border-white/15 bg-black/25 px-3 py-2 text-xs outline-none focus:border-f1" /><select value={input} onChange={(event) => setInput(event.target.value)} className="border border-white/15 bg-black/25 px-3 py-2 text-xs"><option value="">All inputs</option><option>Wheel / Direct Drive</option><option>Wheel / Belt Drive</option><option>Controller</option><option>Keyboard</option></select><select value={assists} onChange={(event) => setAssists(event.target.value)} className="border border-white/15 bg-black/25 px-3 py-2 text-xs"><option value="">All assists</option><option>Unspecified</option><option>No assists</option><option>Custom</option></select><select value={weather} onChange={(event) => setWeather(event.target.value)} className="border border-white/15 bg-black/25 px-3 py-2 text-xs"><option value="">All weather</option><option>Clear</option><option>Light cloud</option><option>Overcast</option><option>Light rain</option><option>Heavy rain</option><option>Storm</option></select></div>{laps.length ? <ol className="timing-grid font-timing text-sm">{laps.map((lap, index) => <li key={lap.id} className="grid grid-cols-[3rem_1fr_auto] items-center border-t border-white/[.06] px-4 py-3"><b className="text-f1">{index + 1}</b><span><b>{lap.gamertag || lap.driver_name}</b><small className="ml-2 text-zinc-500">{lap.car} · {lap.input_setup} · {lap.weather}</small></span><b>{formatMs(lap.lap_time_ms)}</b></li>)}</ol> : <p className="px-4 py-8 text-center text-sm text-zinc-500">No verified laps match these filters yet.</p>}</section>;
}
