"use client";

import { useEffect, useMemo, useState } from "react";
import type { User } from "@supabase/supabase-js";
import { formatMs, type TrackInfo } from "@/lib/telemetry";
import { supabase } from "@/lib/supabase/client";

type Lap = { id: string; track_name: string; car: string; lap_time_ms: number; sector1_ms: number | null; sector2_ms: number | null; sector3_ms: number | null; recorded_at: string; source_verified: boolean };
const average = (values: number[]) => values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : 0;
const deviation = (values: number[]) => values.length > 1 ? Math.sqrt(average(values.map((value) => (value - average(values)) ** 2))) : 0;

function PaceChart({ laps }: { laps: Lap[] }) {
  const points = [...laps].reverse().slice(-12);
  if (points.length < 2) return <div className="grid h-28 place-items-center text-xs text-zinc-500">Drive at least two verified laps to chart consistency.</div>;
  const times = points.map((lap) => lap.lap_time_ms), min = Math.min(...times), max = Math.max(...times), range = Math.max(1, max - min);
  const plot = points.map((lap, index) => `${(index / (points.length - 1)) * 300 + 10},${12 + ((lap.lap_time_ms - min) / range) * 78}`).join(" ");
  return <svg viewBox="0 0 320 112" className="h-28 w-full" role="img" aria-label="Recent lap-time consistency"><line x1="10" y1="90" x2="310" y2="90" stroke="#3f3f46" /><polyline points={plot} fill="none" stroke="#e10600" strokeWidth="3" strokeLinejoin="round" strokeLinecap="round" />{points.map((lap, index) => <circle key={lap.id} cx={(index / (points.length - 1)) * 300 + 10} cy={12 + ((lap.lap_time_ms - min) / range) * 78} r="3.5" fill="#f5f5f5" stroke="#e10600" strokeWidth="2" />)}<text x="10" y="106" fill="#71717a" fontSize="9">older</text><text x="282" y="106" fill="#71717a" fontSize="9">latest</text></svg>;
}

export function PersonalDashboard({ user, track }: { user: User | null; track: TrackInfo }) {
  const [laps, setLaps] = useState<Lap[]>([]);
  useEffect(() => { const client = supabase; if (!client || !user) return; const load = () => client.from("laps").select("id,track_name,car,lap_time_ms,sector1_ms,sector2_ms,sector3_ms,recorded_at,source_verified").eq("user_id", user.id).eq("valid", true).eq("source_verified", true).order("recorded_at", { ascending: false }).limit(100).then(({ data }) => setLaps(data || [])); void load(); const channel = client.channel(`driver-garage-${user.id}`).on("postgres_changes", { event: "INSERT", schema: "public", table: "laps", filter: `user_id=eq.${user.id}` }, load).subscribe(); return () => { client.removeChannel(channel); }; }, [user]);
  const summary = useMemo(() => {
    const times = laps.map((lap) => lap.lap_time_ms), current = laps.filter((lap) => lap.track_name === track.name), sectors = ["sector1_ms", "sector2_ms", "sector3_ms"] as const;
    const sectorGain = sectors.reduce((total, key) => { const values = laps.map((lap) => lap[key]).filter((value): value is number => typeof value === "number" && value > 0); return total + (values.length ? average(values) - Math.min(...values) : 0); }, 0);
    const bestByTrack = Object.entries(laps.reduce<Record<string, number>>((best, lap) => ({ ...best, [lap.track_name]: Math.min(best[lap.track_name] || Infinity, lap.lap_time_ms) }), {})).sort((a, b) => a[1] - b[1]).slice(0, 4);
    const sessions = Object.values(laps.reduce<Record<string, { key: string; track: string; count: number; best: number }>>((all, lap) => { const date = new Date(lap.recorded_at).toLocaleDateString(); const key = `${date}-${lap.track_name}`; const old = all[key]; return { ...all, [key]: { key: date, track: lap.track_name, count: (old?.count || 0) + 1, best: Math.min(old?.best || Infinity, lap.lap_time_ms) } }; }, {})).slice(0, 5);
    return { average: average(times), consistency: deviation(times), sectorGain, currentBest: current.length ? Math.min(...current.map((lap) => lap.lap_time_ms)) : 0, bestByTrack, sessions };
  }, [laps, track.name]);
  if (!user || !supabase) return null;
  return <section className="mt-5 overflow-hidden border border-white/10 bg-panel"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-white/10 px-4 py-3"><div><p className="text-[10px] font-bold uppercase tracking-[.22em] text-f1">Driver garage</p><h2 className="text-xl font-bold uppercase">Personal performance</h2></div><p className="max-w-sm text-right text-[10px] uppercase text-zinc-500">Verified laps only · up to latest 100 attempts</p></div>{laps.length ? <><div className="grid gap-px bg-white/10 sm:grid-cols-2 lg:grid-cols-4"><Metric label={`${track.name} PB`} value={formatMs(summary.currentBest)} /><Metric label="Average pace" value={formatMs(summary.average)} /><Metric label="Consistency" value={`±${formatMs(summary.consistency, false)}`} /><Metric label="Sector opportunity" value={`−${formatMs(summary.sectorGain, false)}`} /></div><div className="grid gap-5 p-4 lg:grid-cols-[1.1fr_.9fr]"><div className="border border-white/10 bg-black/15 p-4"><div className="mb-2 flex justify-between"><h3 className="text-sm font-bold uppercase">Consistency</h3><span className="text-[10px] uppercase text-zinc-500">Last {Math.min(laps.length, 12)} laps</span></div><PaceChart laps={laps} /></div><div className="border border-white/10 bg-black/15 p-4"><h3 className="mb-3 text-sm font-bold uppercase">PB by circuit</h3><div className="space-y-2 font-timing text-xs">{summary.bestByTrack.map(([name, time]) => <div key={name} className="flex justify-between gap-3 border-b border-white/[.07] pb-2"><span className="truncate text-zinc-300">{name}</span><b>{formatMs(time)}</b></div>)}</div></div></div><div className="border-t border-white/10"><div className="flex items-center justify-between px-4 py-3"><h3 className="text-sm font-bold uppercase">Recent sessions</h3><span className="text-[10px] uppercase text-zinc-500">Date and circuit grouping</span></div><ol className="font-timing text-sm">{summary.sessions.map((session) => <li key={`${session.key}-${session.track}`} className="grid grid-cols-[1fr_auto] items-center border-t border-white/[.06] px-4 py-3"><span><b>{session.track}</b><small className="ml-2 text-zinc-500">{session.key} · {session.count} laps</small></span><b>{formatMs(session.best)}</b></li>)}</ol></div></> : <p className="px-4 py-10 text-center text-sm text-zinc-500">No verified laps yet. Generate a relay link, restart the listener, then complete a valid lap to unlock your performance dashboard.</p>}</section>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="bg-panel px-4 py-4"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-zinc-500">{label}</p><b className="mt-1 block font-timing text-2xl">{value || "—"}</b></div>; }
